[platformio]
src_dir = ClassQuizServer
default_envs = esp32s3

; ESP32-S3-N16R8: 16MB 四线 Flash + 8MB 八线 PSRAM
[env:esp32s3]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
build_flags =
    -DBOARD_HAS_PSRAM
monitor_speed = 115200
upload_speed = 921600
